# Generated by Django 6.1.1 on 2026-09-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='取消勾选后前台不显示', verbose_name='发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('slug', models.SlugField(help_text='拼音或英文，如 zhang-wei', max_length=80, unique=True, verbose_name='URL 文件名')),
                ('name', models.CharField(max_length=60, verbose_name='姓名')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='英文名 / 拼音')),
                ('role', models.CharField(choices=[('导师', '导师'), ('博士后', '博士后'), ('博士生', '博士生'), ('硕士生', '硕士生'), ('本科生', '本科生'), ('科研助理', '科研助理'), ('校友', '校友')], default='博士生', max_length=20, verbose_name='身份')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='职称 / 年级')),
                ('order', models.IntegerField(default=99, help_text='数字越小越靠前', verbose_name='组内排序')),
                ('photo', models.CharField(blank=True, help_text='如 /images/team/xxx.jpg；留空则显示姓名首字头像', max_length=300, verbose_name='照片路径')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('join_year', models.CharField(blank=True, max_length=10, verbose_name='加入年份')),
                ('interests', models.JSONField(blank=True, default=list, verbose_name='研究兴趣')),
                ('links', models.JSONField(blank=True, default=dict, help_text='JSON 对象，支持 homepage / scholar / github / orcid / dblp', verbose_name='相关链接')),
                ('bio', models.TextField(blank=True, verbose_name='个人简介（Markdown）')),
            ],
            options={
                'verbose_name': '团队成员',
                'verbose_name_plural': '团队成员',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='取消勾选后前台不显示', verbose_name='发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('slug', models.SlugField(help_text='英文短名，如 cvpr-2026-papers', max_length=120, unique=True, verbose_name='URL 文件名')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('date', models.DateField(verbose_name='发布日期')),
                ('summary', models.TextField(blank=True, help_text='列表页显示', verbose_name='摘要')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('cover', models.CharField(blank=True, max_length=300, verbose_name='封面图路径')),
                ('pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('body', models.TextField(blank=True, verbose_name='正文（Markdown）')),
            ],
            options={
                'verbose_name': '科研新闻',
                'verbose_name_plural': '科研新闻',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='取消勾选后前台不显示', verbose_name='发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL 文件名')),
                ('title', models.CharField(help_text='论文标题请用英文原文', max_length=400, verbose_name='成果标题')),
                ('authors', models.JSONField(blank=True, default=list, verbose_name='作者列表')),
                ('venue', models.CharField(max_length=300, verbose_name='期刊 / 会议全称')),
                ('venue_short', models.CharField(blank=True, help_text='如 CVPR', max_length=60, verbose_name='简称')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('type', models.CharField(choices=[('期刊论文', '期刊论文'), ('会议论文', '会议论文'), ('预印本', '预印本'), ('专利', '专利'), ('专著', '专著'), ('获奖', '获奖'), ('项目', '项目')], default='会议论文', max_length=20, verbose_name='成果类型')),
                ('area', models.CharField(blank=True, help_text='填「研究方向」的中文标题，才会在该方向详情页关联显示', max_length=120, verbose_name='所属研究方向')),
                ('highlight', models.BooleanField(default=False, help_text='勾选后会出现在首页「代表性成果」', verbose_name='设为精选')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='原文链接')),
                ('pdf', models.URLField(blank=True, max_length=500, verbose_name='PDF 链接')),
                ('code', models.URLField(blank=True, max_length=500, verbose_name='代码仓库')),
                ('abstract', models.TextField(blank=True, verbose_name='简介')),
            ],
            options={
                'verbose_name': '科研成果',
                'verbose_name_plural': '科研成果',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='取消勾选后前台不显示', verbose_name='发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('slug', models.SlugField(help_text='英文小写短横线，如 computer-vision', max_length=80, unique=True, verbose_name='URL 文件名')),
                ('title', models.CharField(max_length=120, verbose_name='中文标题')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='英文标题')),
                ('summary', models.TextField(help_text='显示在卡片上', verbose_name='一句话简介')),
                ('icon', models.CharField(default='🔬', max_length=16, verbose_name='图标 emoji')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='JSON 数组，如 ["目标检测", "图像分割"]', verbose_name='关键词')),
                ('order', models.IntegerField(default=99, help_text='数字越小越靠前', verbose_name='排序')),
                ('cover', models.CharField(blank=True, help_text='如 /images/research/xxx.jpg', max_length=300, verbose_name='配图路径')),
                ('body', models.TextField(blank=True, verbose_name='正文（Markdown）')),
            ],
            options={
                'verbose_name': '研究方向',
                'verbose_name_plural': '研究方向',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='某某实验室', max_length=120, verbose_name='课题组名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('abbr', models.CharField(default='LAB', help_text='2-5 个字母，显示在 Logo 上', max_length=12, verbose_name='缩写')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='一句话简介')),
                ('affiliation', models.CharField(blank=True, max_length=200, verbose_name='所属单位')),
                ('description', models.TextField(blank=True, verbose_name='搜索引擎简介')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='通讯地址')),
                ('postcode', models.CharField(blank=True, max_length=20, verbose_name='邮编')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='电子邮箱')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='联系电话')),
                ('openings_enabled', models.BooleanField(default=True, verbose_name='显示招生信息')),
                ('openings_title', models.CharField(blank=True, max_length=200, verbose_name='招生标题')),
                ('openings_text', models.TextField(blank=True, verbose_name='招生说明')),
                ('openings_email', models.EmailField(blank=True, max_length=254, verbose_name='接收申请邮箱')),
                ('nav', models.JSONField(blank=True, default=list, help_text='JSON 数组，如 [{"label": "首页", "href": "/"}]；留空则使用默认菜单', verbose_name='导航菜单')),
                ('social', models.JSONField(blank=True, default=list, verbose_name='页脚链接')),
                ('icp', models.CharField(blank=True, max_length=60, verbose_name='备案号')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
            },
        ),
    ]
