# Generated by Django 6.1.1 on 2026-09-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='存储路径')),
                ('content_type', models.CharField(default='image/jpeg', max_length=80, verbose_name='MIME 类型')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='字节数')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='宽')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='高')),
                ('data', models.BinaryField(verbose_name='文件内容')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '图片文件',
                'verbose_name_plural': '图片文件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
