# Generated by Django 6.1.1 on 2026-09-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesetting_group_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='areas',
            field=models.JSONField(blank=True, default=list, help_text='JSON 数组，填「研究方向」的中文标题，如 ["计算机视觉"]；会在对应方向详情页展示', verbose_name='所属研究方向'),
        ),
        migrations.AddField(
            model_name='member',
            name='now_at',
            field=models.CharField(blank=True, help_text='例如「某大学 助理教授」「某公司 算法工程师」；校友填写后会在成员页突出显示', max_length=160, verbose_name='现在在哪 / 毕业去向'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='openings_details',
            field=models.TextField(blank=True, help_text='可写申请材料清单、流程、常见问题；支持 Markdown 列表与链接', verbose_name='招生详情（Markdown）'),
        ),
        migrations.AlterField(
            model_name='member',
            name='achievement_summary',
            field=models.TextField(blank=True, help_text='用通俗语言写论文、项目或比赛成果', verbose_name='成果产出'),
        ),
        migrations.AlterField(
            model_name='member',
            name='research_focus',
            field=models.CharField(blank=True, max_length=200, verbose_name='主要研究方向'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='openings_text',
            field=models.TextField(blank=True, help_text='一两句话说明在招什么方向的人', verbose_name='招生说明'),
        ),
    ]
