# Generated by Django 6.1.1 on 2026-09-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_member_areas_member_now_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='取消勾选后前台不显示', verbose_name='发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('title_en', models.CharField(blank=True, help_text='显示在中文标题下方，可留空', max_length=300, verbose_name='英文副标题')),
                ('summary', models.TextField(blank=True, help_text='一两句话介绍这一屏在讲什么', verbose_name='说明文字')),
                ('image', models.CharField(blank=True, help_text='建议横向大图；留空则使用内置渐变背景', max_length=500, verbose_name='背景图')),
                ('link', models.CharField(blank=True, help_text='站内路径（如 /research）或完整 http(s) 地址；留空则不显示按钮', max_length=300, verbose_name='按钮链接')),
                ('link_label', models.CharField(blank=True, help_text='留空则用「了解更多」', max_length=60, verbose_name='按钮文字')),
                ('order', models.IntegerField(default=99, help_text='数字越小越靠前', verbose_name='排序')),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, default='博士生', help_text='常用取值见输入框建议；也可以自己填，例如「访问学者」「联合培养博士」。成员页的分组顺序在「站点设置 → 成员页文案 → 身份分组顺序」里调整。', max_length=30, verbose_name='身份'),
        ),
    ]
