# Generated by Django 6.1.1 on 2026-09-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_homeslide_alter_member_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=True, help_text='取消勾选后前台不显示', verbose_name='发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL 文件名')),
                ('name', models.CharField(max_length=300, verbose_name='项目名称')),
                ('category', models.CharField(blank=True, help_text='常用：国家级项目 / 省部级项目 / 基金项目 / 企业合作 / 国际合作；也可以自己填。', max_length=40, verbose_name='项目类别')),
                ('sponsor', models.CharField(blank=True, help_text='如 国家自然科学基金委员会', max_length=200, verbose_name='资助机构')),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='项目编号')),
                ('role', models.CharField(blank=True, help_text='如 主持 / 参与 / 子课题负责人', max_length=40, verbose_name='承担角色')),
                ('leader', models.CharField(blank=True, max_length=120, verbose_name='负责人')),
                ('members', models.JSONField(blank=True, default=list, help_text='每行一位，填「团队成员」里的姓名；会在项目页链接到对应成员。', verbose_name='参与成员')),
                ('start_year', models.IntegerField(blank=True, null=True, verbose_name='起始年份')),
                ('end_year', models.IntegerField(blank=True, help_text='在研项目可以留空', null=True, verbose_name='结束年份')),
                ('status', models.CharField(blank=True, help_text='常用：在研 / 已结题；留空则只显示起止年份。', max_length=20, verbose_name='状态')),
                ('amount', models.CharField(blank=True, help_text='可留空。不方便公开就不填，前台不会显示这一行。', max_length=60, verbose_name='经费')),
                ('summary', models.TextField(blank=True, help_text='两三句话说明研究问题与目标', verbose_name='项目简介')),
                ('link', models.CharField(blank=True, help_text='站内路径或完整 http(s) 地址；留空则不显示按钮。', max_length=300, verbose_name='项目主页链接')),
                ('order', models.IntegerField(default=99, help_text='同一年份内数字越小越靠前', verbose_name='排序')),
                ('body', models.TextField(blank=True, verbose_name='详细说明（Markdown）')),
            ],
            options={
                'verbose_name': '科研项目',
                'verbose_name_plural': '科研项目',
                'ordering': ['-start_year', 'order', 'id'],
            },
        ),
    ]
